WINDOW_SIZE = 900
BOARD_SIZE = 8

DISCONNECT_USER = "DISCONNECT_USER"
ASSIGN_COLOR = "ASSIGN_COLOR"
SERVER_DISCONNECTED = "SERVER_DISCONNECTED"
WAITING_FOR_USER = "WAITING_FOR_USER"
OPPONENT_DISCONNECTED = "OPPONENT_DISCONNECTED"
OPPONENT_CONNECTED = "OPPONENT_CONNECTED"
IS_OPPONENT_CONNECTED = "IS_OPPONENT_CONNECTED"
OPPONENT_CONNECTING = "OPPONENT_CONNECTING"
